### ISSUE TITLE
Week 10 assignment is done!

### ISSUE THREAD

**Issue by ldunne-matc** [madisoncollege-it-programs/python-scripting-ldunne-matc#10]

**Comment by cethenmc** [comment]
I am so sorry, I did not see this out there earlier.  Not sure how I missed it.

Mostly good, until the confusion just at the end.  You printed the list without the header.  It wanted the whole list still with the All caps header at the top.  It just wanted the length of the slice that did not include the header.  Due to the missing length, -1 point.

7 out of 8.  Please feel free to resubmit for the additional point.  However, your first focus should be finishing the Final Project by Thursday night!

Thanks.

Chris

**Comment by cethenmc** [comment]
Time expired in the session, and I did not see any future attempt at correcting.  Closing ticket.
