### ISSUE TITLE
Week1 Git lab ready to grade!

### ISSUE THREAD

**Issue by ldunne-matc** [madisoncollege-it-programs/python-scripting-ldunne-matc#2]

**Comment by cethenmc** [comment]
Hi, Logan.  There were a couple of misses in this exercise.  If you reverted the filetorevert.txt it would not have shown in ls.txt at the end.  I could tell you got the basic concept of reverting to a previous commit, which is the main concept of that exercise.  Just for house keeping, my automated file checker did not find gitlogafter.txt because of a misspelling you had.  Please be careful to follow the instructions.  Because you understood the concept, I will be lenient on this one and still give full credit.  Please be careful in the future.  ~Chris
