### ISSUE TITLE
Week 5 Assignment done

### ISSUE THREAD

**Issue by ldunne-matc** [madisoncollege-it-programs/python-scripting-ldunne-matc#5]

**Comment by cethenmc** [comment]
Hi, Logan.  Are you certain you completed this assignment?  I do not see a script named files.py.  Any files that are in week5 are not executable at the command line level.  Please follow instructions, make the file executable at the command line level, and resubmit.  Thanks.  Chris

**Comment by cethenmc** [comment]
Hi, Logan.  Fairly nice work on the first two; you are missing the third one.  Also, since you will be finishing the third one, could you  also describe the len() function in #2 (the readlines() one) how the "items in the list" relate to the file?

Please don't hesitate to reach out on #3.  The key is to not use readline() and readlines() because they were already used in problem 1 and 2 for this assignment.  Also, ensure that with each line you read, you append it to a variable.  This allows you to satisfy the requirement to save the entire content to a variable one line at a time.

For now I will record this assignment as 5 of 8.  When you complete this assignment, please reply to this issue telling me to regrade it.  

Thanks.

Chris

**Comment by cethenmc** [comment]
Thanks for meeting today.  Please reply to **each** issue when you have repushed to GitHub your corrections!  ~Chris

**Comment by cethenmc** [comment]
Thanks for meeting today.  I will ignore that you did not remove this line in number 3 that we worked on today:  print("This len() funtion is counting the items in the list.")
 
Also, you should have modified the explanation for #3.  Remember, we copied from 2?   Actually, my apologies, Logan!  I just realized that you were probably not ready for me to look at them yet.  You had not replied to this ticket saying you were ready for me to regrade.  I will wait for that.

**Comment by cethenmc** [comment]
You just have to readjust the explanation on this one

**Comment by cethenmc** [comment]
Logan - This still needs work to regain points.  We even went through 3 together.  However, your explanations need work.  

The red circles should explain when you would use the specific read function you chose (read(), readlines(), readline(), respectively).  In the first and second red circles, you explained more about the len() function than the read function you used.  In the third, you just copied the second red circle.

The green font (I highlighted the letters green) does not need to be there.  You aren't asked to tell what the length is counting that time because it was already answered in 1. 

![image](https://user-images.githubusercontent.com/112707666/199647316-0f9ea441-89ac-4971-9bf6-aa5a81e94e25.png)

**Comment by ldunne-matc** [comment]
Done! Please tell me if it did not go through!

**Comment by cethenmc** [comment]
Logan - This one never went through.  I see the same explanations that were in my last screen shot.

**Comment by cethenmc** [comment]
Sorry.  I take that back.  I see that you modified **one** of the three explanations.  Changing the score from a 5 out of 8 to 6 out of 8 and closing this ticket.
