### ISSUE TITLE
midterms are done!

### ISSUE THREAD

**Issue by ldunne-matc** [madisoncollege-it-programs/python-scripting-ldunne-matc#8]

**Comment by cethenmc** [comment]
- Midterm-if:  All concepts you used were concepts learned in class, which was nice to see.  I like that you analyzed your data carefully to identify the column structure in the flat file.  Perhaps you had to analyze too much to creatively come up with the correct line numbers (instead of extracting them like required you counted them (2 pts), and there was a required note that asked you to convert the extraction to an int to help give a hint (2 pts).  You did not use elifs as required (2 pts).  Without the use of elifs, what would happen if a single line included two key words.  For example, change Lanie Whiteland to Kayley Whiteland.  It would make your result 2436, adding that line's value to your total twice.  For every line of the file, you evaluate each keyword every time, instead of just stopping that line once you found one of them.  It diminishes efficiency.  Your score for this part is 27/33.

- Midterm-jpark:  Nice effort.  The first thing I observed was failed logins.  You did not include the counter on the first two failed tries (1 pt).  The Author name should have been in your comment block, besides the print out to the screen.  I will not take off this time.  The hard coded evaluation (in flow code) could be simplifed and compared to the command_database dictionary (2 pts).  You are also doing some excessive work and evaluation with white_rabbit_object that is not needed (1 pt).  29/33.

- Midterm-slicing:  Thanks for putting forth effort on this one. You did some nice things, but you made things quite complicated.  The fact that you looped and assembled your own list showed a lack of understanding of the power of various read functions (3 pts).  The words you found through slicing did not follow the nature of the requirements.  On three of them you were supposed to start from the back of the file (6 pts).  Coming out of the slicing, you embedded lists in lists making it more complicated for yourself (2 pts), and then there was uncertainty with how to best use the join (2 pts).  I recommend you revisiting slicing.  23/34.
